BEGIN TRANSACTION;
ALTER TABLE [TB_ARMA] DROP CONSTRAINT [FK_TB_ARMA_TB_PERSONAGENS_PersonagemId];

ALTER TABLE [TB_PERSONAGENS] DROP CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_UsuarioId];

ALTER TABLE [TB_PERSONAGENS] DROP CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_usuarioId];

DROP INDEX [IX_TB_PERSONAGENS_UsuarioId] ON [TB_PERSONAGENS];

DROP INDEX [IX_TB_ARMA_PersonagemId] ON [TB_ARMA];

DECLARE @var sysname;
SELECT @var = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[TB_PERSONAGENS]') AND [c].[name] = N'UsuarioId');
IF @var IS NOT NULL EXEC(N'ALTER TABLE [TB_PERSONAGENS] DROP CONSTRAINT [' + @var + '];');
ALTER TABLE [TB_PERSONAGENS] DROP COLUMN [UsuarioId];

EXEC sp_rename N'[TB_PERSONAGENS].[usuarioId]', N'UsuarioId', 'COLUMN';

EXEC sp_rename N'[TB_PERSONAGENS].[IX_TB_PERSONAGENS_usuarioId]', N'IX_TB_PERSONAGENS_UsuarioId', 'INDEX';

DECLARE @var1 sysname;
SELECT @var1 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[TB_ARMA]') AND [c].[name] = N'PersonagemId');
IF @var1 IS NOT NULL EXEC(N'ALTER TABLE [TB_ARMA] DROP CONSTRAINT [' + @var1 + '];');
UPDATE [TB_ARMA] SET [PersonagemId] = 0 WHERE [PersonagemId] IS NULL;
ALTER TABLE [TB_ARMA] ALTER COLUMN [PersonagemId] int NOT NULL;
ALTER TABLE [TB_ARMA] ADD DEFAULT 0 FOR [PersonagemId];

CREATE TABLE [TB_HABILIDADES] (
    [Id] int NOT NULL IDENTITY,
    [Nome] varchar(200) NOT NULL,
    [Dano] int NOT NULL,
    CONSTRAINT [PK_TB_HABILIDADES] PRIMARY KEY ([Id])
);

CREATE TABLE [TB_PERSONAGENS_HABILIDADES] (
    [PersonagemId] int NOT NULL,
    [HabilidadeId] int NOT NULL,
    CONSTRAINT [PK_TB_PERSONAGENS_HABILIDADES] PRIMARY KEY ([PersonagemId], [HabilidadeId]),
    CONSTRAINT [FK_TB_PERSONAGENS_HABILIDADES_TB_HABILIDADES_HabilidadeId] FOREIGN KEY ([HabilidadeId]) REFERENCES [TB_HABILIDADES] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_PERSONAGENS_HABILIDADES_TB_PERSONAGENS_PersonagemId] FOREIGN KEY ([PersonagemId]) REFERENCES [TB_PERSONAGENS] ([Id]) ON DELETE CASCADE
);

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Dano', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_HABILIDADES] ON;
INSERT INTO [TB_HABILIDADES] ([Id], [Dano], [Nome])
VALUES (1, 20, 'Invocar o pai'),
(2, 10, 'Arremeço de pastel'),
(3, 30, 'Choque do trovão'),
(4, 15, 'Saque de volei');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Dano', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_HABILIDADES] OFF;

UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 2;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 3;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 4;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 5;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 6;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [UsuarioId] = 1
WHERE [Id] = 7;
SELECT @@ROWCOUNT;


UPDATE [TB_USUARIO] SET [PasswordHash] = 0xEEEA575CA08022875EE8286D23680C502340E63AD9A4EB0FD102443102D647F33F3C3D6AD5DA4824592C966C2F57D7C32670665D6F211BB2C4ED05A97231770F, [PasswordSalt] = 0xDB94FF5E6B3E913442089A7800D8AE196CFEE2D4AAC2575B0CFB49BEA95832C40FB5E39E354F11759E9BAAA0337DCB545BAF2A509F73505C8057C3B62ED3FAC6219FAFBFCA0FF7F2890E543CA40F56FC228A4DD856F41F6F804A793354026330032BC2C9CFA83E60CBA2FAA50AC8E485BCB37BD32F115DEE348510A0AFB459FC
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'HabilidadeId', N'PersonagemId') AND [object_id] = OBJECT_ID(N'[TB_PERSONAGENS_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_PERSONAGENS_HABILIDADES] ON;
INSERT INTO [TB_PERSONAGENS_HABILIDADES] ([HabilidadeId], [PersonagemId])
VALUES (1, 1),
(1, 2),
(2, 3),
(3, 4),
(1, 5),
(1, 6),
(4, 7);
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'HabilidadeId', N'PersonagemId') AND [object_id] = OBJECT_ID(N'[TB_PERSONAGENS_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_PERSONAGENS_HABILIDADES] OFF;

CREATE UNIQUE INDEX [IX_TB_ARMA_PersonagemId] ON [TB_ARMA] ([PersonagemId]);

CREATE INDEX [IX_TB_PERSONAGENS_HABILIDADES_HabilidadeId] ON [TB_PERSONAGENS_HABILIDADES] ([HabilidadeId]);

ALTER TABLE [TB_ARMA] ADD CONSTRAINT [FK_TB_ARMA_TB_PERSONAGENS_PersonagemId] FOREIGN KEY ([PersonagemId]) REFERENCES [TB_PERSONAGENS] ([Id]) ON DELETE CASCADE;

ALTER TABLE [TB_PERSONAGENS] ADD CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_UsuarioId] FOREIGN KEY ([UsuarioId]) REFERENCES [TB_USUARIO] ([Id]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20251008001108_MigracaoMuitosParaMuitos', N'9.0.9');

COMMIT;
GO

