BEGIN TRANSACTION;
ALTER TABLE [TB_PERSONAGENS] DROP CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_UsuarioId];

EXEC sp_rename N'[TB_PERSONAGENS].[UsuarioId]', N'usuarioId', 'COLUMN';

EXEC sp_rename N'[TB_PERSONAGENS].[IX_TB_PERSONAGENS_UsuarioId]', N'IX_TB_PERSONAGENS_usuarioId', 'INDEX';

ALTER TABLE [TB_PERSONAGENS] ADD [Derrotas] int NOT NULL DEFAULT 0;

ALTER TABLE [TB_PERSONAGENS] ADD [Disputas] int NOT NULL DEFAULT 0;

ALTER TABLE [TB_PERSONAGENS] ADD [UsuarioId] int NULL;

ALTER TABLE [TB_PERSONAGENS] ADD [Vitorias] int NOT NULL DEFAULT 0;

ALTER TABLE [TB_ARMA] ADD [PersonagemId] int NULL;

UPDATE [TB_ARMA] SET [PersonagemId] = 1
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 2
WHERE [Id] = 2;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 3
WHERE [Id] = 3;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 4
WHERE [Id] = 4;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 5
WHERE [Id] = 5;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 6
WHERE [Id] = 6;
SELECT @@ROWCOUNT;


UPDATE [TB_ARMA] SET [PersonagemId] = 7
WHERE [Id] = 7;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 2;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 3;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 4;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 5;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 6;
SELECT @@ROWCOUNT;


UPDATE [TB_PERSONAGENS] SET [Derrotas] = 0, [Disputas] = 0, [UsuarioId] = 1, [Vitorias] = 0, [usuarioId] = NULL
WHERE [Id] = 7;
SELECT @@ROWCOUNT;


UPDATE [TB_USUARIO] SET [PasswordHash] = 0x8FE42673CFFF29E95EC9CEE5421852D42D378509614621C91F581AF1BEED50B5F8729EE161063AA8EC3814D45BBCAD90CDBDC472F6666CCEFC4961B5C2377DFD, [PasswordSalt] = 0x8AB2FF094D3BD88284A45F4C6277C23F0BAE8E7FFD0DA89B080C12C0E2F58FD97A47A8AFB44D1366D8E97D9B912741BD63EFEA0F664998B0CDBECDFE725B917353F1F77CA4042329B068FB3359302D54DAD3BB4D25BDC9C85E66555A8632E9861C0C83EDC4BFE7A526BB59A6CE70F1DE8A22F6D12D29C433C69021D531BEE6CB
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


CREATE INDEX [IX_TB_PERSONAGENS_UsuarioId] ON [TB_PERSONAGENS] ([UsuarioId]);

CREATE UNIQUE INDEX [IX_TB_ARMA_PersonagemId] ON [TB_ARMA] ([PersonagemId]) WHERE [PersonagemId] IS NOT NULL;

ALTER TABLE [TB_ARMA] ADD CONSTRAINT [FK_TB_ARMA_TB_PERSONAGENS_PersonagemId] FOREIGN KEY ([PersonagemId]) REFERENCES [TB_PERSONAGENS] ([Id]);

ALTER TABLE [TB_PERSONAGENS] ADD CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_UsuarioId] FOREIGN KEY ([UsuarioId]) REFERENCES [TB_USUARIO] ([Id]);

ALTER TABLE [TB_PERSONAGENS] ADD CONSTRAINT [FK_TB_PERSONAGENS_TB_USUARIO_usuarioId] FOREIGN KEY ([usuarioId]) REFERENCES [TB_USUARIO] ([Id]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20251001231231_MigracaoUmParaUm', N'9.0.9');

COMMIT;
GO

